### PR TITLE
Adds `many/p` combinator with count and sep keyword args

### LINKED ISSUE #3: Feature request: `many/p` that allows specifying a minimum and/or maximum count
I'd like a parser that's like `many/p` except instead of "zero/one or more times", I want to specify "at least N times and at most M times" (this came up while implementing some parsers for DNS addresses). Is this something that belongs in Megaparsack or a separate "more parsers" package?

I've implemented a version of this on my fork that works with keyword arguments, it looks like `(many/p p #:min-count n #:max-count m #:separator sep)`. The defaults of the keyword args make it a superset of the behavior provided by `many*/p`, `many+/p`, `many*/sep/p`, `many+/sep/p`, and `repeat/p`. I personally like using one procedure with defaulted keyword args instead of the existing swarm of procedures, but I'm fine implementing this as a one off alongside the others (or in another package).

### PR DESCRIPTION
**Pull request by jackfirth**
Closes #3. Builds on top of #8, hence the duplicated commits.

The commits for this PR are broken into two sections: adding `many/p` and deprecating the various `many*/p`, `many/sep/p`, etc. variants that this subsumes. The last commit publicly replaces uses of the variants in docs with `many/p` and keyword arguments. The second to last commit moves the variants into a separate module to keep them quarantined away from non-deprecated combinators.

Deprecation of the variants is optional. As might be suspected, I'm in favor of deprecation on the grounds that Racket generally encourages using a few keyword arguments on one procedure instead of multiple procedures. If you would rather keep them, I'll remove those commits from this PR.

### CODE REVIEW

**Comment by lexi-lambda** [comment]
This looks good. A couple comments:

  - The keyword arguments are nice, but pretty heavy. I generally favor words over abbreviations, but I think that this loses over the old combinators in verbosity in a few places. Would you be alright with using `#:sep`, `#:min`, and `#:max` instead of the current names?

  - For a similar reason, I think that “1 or more” happens to be an *incredibly* common use case in practice, so I think it might make sense to keep `many+/p` around as non-deprecated that defaults `#:min` to 1.

**Comment by jackfirth** [comment]
- Shorter keywords do look nicer, I'll rename them.
- Keeping `many+/p` around sounds reasonable. Should it accept the same `#:sep` and `#:max` arguments?

**Comment by lexi-lambda** [comment]
Yes, I think keeping those options available would make sense. Obviously no point in accepting `#:min`, though.

**Comment by lexi-lambda** [comment]
Merged in db991de9ace374d84ee34271b0c6d23b8e99294e and f8827a25357e8b4b6f496cfd28a2bf9a301c776c. Thanks for the work! I agree this interface is a lot nicer.

**Pull request closed without merging**
