### PR TITLE
Add `char-in/p` and `char-between/p`

### LINKED ISSUE #5: Feature request: `char-between/p` and `char-in/p`
These are simple utilities for parsing character ranges:

```racket
(define ascii-digit/p (char-between/p #\0 #\1))
(define ascii-vowel/p (char-in/p "aeiou"))
```

As with #3 and #4, I've implemented these and wanted to know if they'd be welcomed in `megaparsack/text`

### PR DESCRIPTION
**Pull request by jackfirth**
Closes #5

### CODE REVIEW

**Comment by lexi-lambda** [comment]
I’m not inherently opposed to `char-in/p`, but is there are reason to prefer it over a `one-of/p` that would be used like `(one-of/p '(#\a #\b #\c))`? I think representing a list of characters *as* a list of characters instead of a string is a little less confusing. Haskell lets you do `oneOf "abc"` because strings *are* lists, but I think that’s a wart more than anything else.

**Comment by jackfirth** [comment]
Using `(one-of/p '(chars ...))` would be enough, but if `many+/p` is common enough to warrant a helper I think `(char-in/p <string>)` is too. Assuming the addition of `one/of`, using strings would be more of a convenience to avoid either writing `#\` a lot of times or adding `string->list`. The error message would be a little uglier with `one-of/p`; it would be easier to read `expected: a character in "aeiou"` instead of `expected: one of '(#\a #\e #\i #\o #\u)`.

**Comment by lexi-lambda** [comment]
I’m not sure the error message argument makes sense to me… that error message seems worse than a simpler one. Since more than one error message is possible, I would prefer this error:

```
expected: ?, +, or an integer
```

…over this one:

```
expected: a character in "?+" or an integer
```

Since megaparsack already handles enumerating possible valid parses, I don’t think an error message should include a sub-enumeration in a separate format. That feels like exposing an implementation detail a user probably doesn’t care about.

**Comment by jackfirth** [comment]
That makes sense, I didn't realize megaparsack handled error messages that way. In that case, `char-in/p` probably doesn't provide much value over `one-of/p`. Would you like me to remove it from this PR?

**Comment by lexi-lambda** [comment]
I realized there actually is some value `char-in/p` can provide, which is to be an abbreviation for `(apply or/p (map char/p v))` instead of `(apply or/p (map ==/p v))`. They parse identically, but there’s one small difference: `char/p` inserts single quotes around its “expected” clause, so you get messages like `'?' or '+'` instead of `? or +`.

I’m not sure if that’s worth having the separate combinator, but if you want to implement that, I’d be alright with merging it. Otherwise, I’d say drop it.

**Comment by jackfirth** [comment]
I'm biased towards keeping it because I have some parsing code already using it, so I'll add that :)

**Comment by lexi-lambda** [comment]
Merged in 245950a24edc3688b7819915afad34888c1525b2.

**Pull request closed without merging**
